language: node_js
node_js:
    - "10"
services:
    - postgresql

addons:
    postgresql: "10"
    apt:
        packages:
            - postgresql-10
            - postgresql-client-10
env:
    global:
        - PGPORT=5433

before_script:
    - psql -c 'create database jobly_test;' -U postgres
    - psql jobly_test < data.sql
script:
    - jest --coverage --runInBand
