language: node_js
node_js:
    - "10"
services:
    - postgresql

addons:
    postgresql: "10"
    apt:
        packages:
            - postgresql-12
            - postgresql-client-12
env:
    global:
        - PGPORT=5433

before_script:
    - psql -c 'create database jobly_test;' -U postgres
    - psql -c jobly_test --file=data.sql
script:
    - jest --coverage --runInBand
